spring:
#File Upload/Download
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB
#Database
  datasource:
    url: jdbc:postgresql://16.8.35.228:5432/fwmanager
    username: browndwarf
    password: browndwarf
#JPA
  jpa:
    #database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql : true
        temp:
          use_jdbc_metadata_defaults: false
#Liquibase
#  liquibase:
    # for Initialization
#    change-log: classpath:/db/changelog-init.xml  
    