spring:
#File Upload/Download
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB
#Database(Main)
  datasource:
    url: jdbc:postgresql://16.8.35.228:5432/fwmanager
    username: browndwarf
    password: browndwarf
#JPA
  jpa:
    #database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql : true
        jdbc: 
          lob: 
            non_contextual_creation: true
#Liquibase
#  liquibase:
    # for Initialization
#    change-log: classpath:/db/changelog-init.xml  

aimscore:
  datasource:
    driver-class-name: org.postgresql.Driver 
    jdbc-url: jdbc:postgresql://16.8.35.228:5432/aimscore
    username: browndwarf
    password: browndwarf
    type: com.zaxxer.hikari.HikariDataSource
    
ota:
  execute:
    duration:
      starthour: 01
      stophour: 05
    intervalminutes: 20  
    